enableGlobalCache: true

initScope: storipress

nodeLinker: node-modules

npmScopes:
  storipress:
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.5.0.cjs
